#include <stdio.h>

//请根据主程序流程，补全此函数
//冰雹产生并输出函数
//注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n) {
	printf("Hailstone generated by %d:\n",n);
	/**********  Begin **********/
	int count=1;
	if(n) {
		printf("%5d\n",n);
		printf("Number of hailstone generated:1");
		return;
	}   else if(!n) {
		printf("%5d",n);
		
		for(count; n!=1; count++) {
			if(n%2==0) {
				n=n/2;
				printf("%5d",n);
			} else if(n%2!=0) {
				n=3*n+1;
				printf("%5d",n);
			}
			if(count%6==0) printf("\n");
		}

	}
	/**********  End  **********/
	printf("\n",n);
	printf("Number of hailstone generated:%d",count);
	
}
